LOGIN_URL = "https://www.namava.ir/api/v1.0/accounts/login/by-phone"
SERIES_DATA = "https://www.namava.ir/api/v2.0/medias/{}/single-series"
EPISODE_DATA = "https://www.namava.ir/api/v1.0/users/seasons/{}/episodes"
MOVIE_DETAIL = "https://www.namava.ir/api2/movie/{}"
USER_DATA = "https://www.namava.ir/api/v1.0/users/info"